import React from 'react'

export default function Bai6() {
  return (
    <div>
        <h1>Bài 6</h1>
        <div className='overflow-x-auto w-[600px] h-[300px] border-solid border-2 border-black-600'>
            <p className=' overflow-hidden inline-block px-4 py-2 mr-4'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium modi accusamus illo optio explicabo quis possimus eaque sint, maiores excepturi velit hic dolorum minus accusantium necessitatibus error natus praesentium ratione?
            Ducimus impedit iste, obcaecati, amet quisquam inventore molestias distinctio fugit perferendis aliquam alias nemo maiores? Voluptatibus omnis, placeat culpa nemo, ducimus, fugiat maxime suscipit assumenda sequi cumque velit! Iure, provident.
            Inventore laudantium, nulla provident nesciunt fuga distinctio porro quaerat reiciendis laboriosam dicta eius quidem deserunt ex laborum, itaque totam repellendus architecto ipsam similique vitae numquam. Libero accusamus odio tempora numquam!
            Dolorem blanditiis non optio. Atque quod, asperiores sunt possimus rem accusamus. Perspiciatis eos ratione perferendis, expedita ipsam commodi error et molestiae placeat quibusdam maiores repudiandae tempora assumenda minus officia harum!
            Blanditiis porro, minima voluptate voluptates velit adipisci sit reiciendis architecto ducimus debitis, perspiciatis provident magnam nam dicta, eaque iste placeat neque vero iure. Et, quis quas alias neque error nihil.
            Corporis harum, assumenda laborum deserunt explicabo at alias minus dicta! Quae maxime voluptatem nemo repellat atque quam? Eos voluptatem repudiandae, natus sit maxime perferendis possimus libero aspernatur ab. Animi, impedit!
            Qui placeat autem quis ex labore delectus maiores. Cupiditate unde libero minus nemo possimus iste beatae architecto aperiam ducimus repudiandae! Minima nostrum magnam in sunt ex sed consectetur veritatis odit.
            Placeat blanditiis nam officiis, veritatis neque eveniet repellat ex rerum corporis, ratione odit! Culpa ea fugit velit. Ullam sapiente eius doloribus optio architecto corporis sint dolor ipsam, error ad commodi?
            Nobis cum culpa neque ea delectus commodi, aspernatur facilis. Et, tempora dolores optio non ipsum sit sed at eligendi quisquam libero voluptas illo ex beatae inventore voluptate vel deleniti animi.
            Eius magni rem in suscipit recusandae! Facere consectetur incidunt provident, hic sunt minus veniam eveniet aspernatur accusantium. Fuga itaque libero fugit excepturi optio, laboriosam saepe amet iste, quisquam a iure.
            Ut quae quibusdam molestiae repellendus officia est, aspernatur qui id asperiores aperiam illum et nostrum, dolor fugiat aliquam, maiores provident? Consectetur dolor assumenda alias voluptates, eveniet fugit consequuntur illum laboriosam!
            At, odit numquam! Asperiores enim architecto, provident neque labore praesentium earum porro vero accusantium accusamus veniam atque sint minus doloremque reiciendis nisi numquam a adipisci placeat iste ipsum dolorum odit?
            Labore repellat quibusdam libero, quae quisquam quas natus, velit tenetur, expedita tempore totam in facere quis placeat voluptatem. Deserunt, ipsam. Quod nisi non ducimus deleniti, magnam dolore quae fugit harum.
            Nulla maxime quam dolorum, placeat reiciendis quibusdam! Velit, voluptas quo repellat odio vel delectus ullam ratione odit earum! Dolores harum omnis vero quisquam porro autem reprehenderit deserunt doloribus aliquid nisi.
            Expedita labore optio molestiae, perferendis vel, enim laboriosam aperiam iusto iste minus necessitatibus voluptatibus voluptates deserunt natus? Repellat nostrum tempora quam, nemo explicabo magni, autem iste debitis quisquam, atque ipsam?
            Illum numquam suscipit quaerat magnam at culpa nemo itaque quasi, aperiam laborum temporibus reiciendis esse aliquam! Quam tenetur possimus, recusandae nesciunt, dolor necessitatibus laboriosam iste cumque fuga excepturi quis dolorem.
            Eveniet dignissimos rem libero earum, reprehenderit velit incidunt vel. Minima, delectus dolore ullam magnam exercitationem sequi nam fuga illum illo blanditiis voluptas necessitatibus eos dignissimos quae deleniti ipsum? Ipsum, ipsam!
            Consequatur temporibus enim deserunt doloribus laborum aut sit distinctio harum ex. Quo dolores, suscipit soluta accusamus eos quam ullam illum. Rem, tempore minima. Delectus est maiores ea quasi laboriosam iusto?
            Qui commodi vitae illo ipsam expedita, provident rem culpa officia delectus! Soluta inventore dolores ducimus vero! Numquam, labore illum natus commodi, enim officiis eveniet magni fuga adipisci possimus dolorum sed.
            Perferendis voluptas rerum eligendi quaerat. Deserunt iure sapiente provident! Laborum suscipit molestiae ipsum nemo incidunt veritatis ad, omnis velit, nam, architecto quasi fugit maxime ipsam deleniti numquam est perspiciatis modi!
            Iusto quasi placeat nam dolorem beatae eaque consectetur. Libero fuga asperiores perferendis, odit officiis dolore recusandae minima iste voluptatem ex numquam eius aliquam, explicabo possimus! Sequi expedita perferendis debitis dolorum!
            Qui facilis adipisci autem obcaecati dolorem facere repellendus modi placeat commodi doloribus provident incidunt soluta a consectetur officia, corporis ullam ex debitis est rem ab cumque voluptatibus. Molestias, eius aliquam.
            Ut dignissimos pariatur similique itaque hic fugiat voluptate tempora sed laboriosam doloremque provident sunt quaerat consectetur, expedita asperiores aspernatur a facilis architecto ad dolorum odit, numquam quam necessitatibus. Ab, eligendi!
            Magni inventore ipsam praesentium porro nesciunt in ratione culpa assumenda quam. Dignissimos, ut dolorum! Omnis necessitatibus quas architecto maxime vitae. Eum a eveniet fugiat nam pariatur quae sequi saepe ab.
            Perferendis molestias sit rem corrupti suscipit maiores id iure, accusantium, hic dolorem excepturi eligendi saepe quasi neque voluptatibus dolor quam iusto cupiditate soluta repudiandae qui nobis ipsum. Libero, facere aut?
            Quae, corporis expedita, fugit veritatis dolor velit animi enim dolorem nam eos nobis. Voluptates enim corrupti similique perspiciatis quos debitis minima qui ipsa nisi, tempora, commodi, quo sapiente dolorum vel.
            Provident corrupti pariatur odio at a iure beatae inventore qui distinctio, id ipsam mollitia sed architecto et ducimus similique consectetur dignissimos? Quibusdam nobis sed amet hic eius. Laborum, ut suscipit!
            Voluptas recusandae iure sed quasi ut similique totam aperiam praesentium repellat obcaecati ea, ab ex odit nemo animi, voluptatum soluta corporis hic voluptatem? A, illum eaque rerum magni explicabo libero.
            Quia magnam tempora molestias blanditiis dolore quis officia non iure. Assumenda debitis nam sequi cum ipsum vero libero totam, maxime est inventore alias accusamus aspernatur molestias rem excepturi. Amet, magnam.
            Laborum animi exercitationem sed explicabo nam odio officia placeat velit sit eius architecto praesentium eum alias deleniti molestiae vitae laboriosam amet vel nemo perspiciatis, provident possimus eaque molestias ab. Ad?
            Assumenda minima soluta dicta ratione odit quisquam non voluptatem repellendus illo, vel perferendis totam, sit, nostrum maiores velit exercitationem molestiae praesentium voluptate consequatur eius obcaecati! Doloribus non minus beatae esse?
            Placeat magni saepe repellat esse minima! Ea possimus corrupti saepe excepturi deleniti, eos doloribus! Commodi provident rem eveniet fugiat similique doloremque sequi, numquam voluptatibus ratione id asperiores! Nam, provident eos.
            Cumque nostrum ea doloremque commodi aliquid tempora reiciendis expedita delectus perspiciatis animi iusto, sint laudantium, aspernatur soluta unde sit ipsa? Odio quos illo est inventore laborum modi quidem tempora voluptatem!
            Delectus maxime eos deleniti quos tempora itaque quam cupiditate voluptatum sit quas. Omnis quae amet porro quaerat voluptatum. Accusamus consequuntur in nesciunt assumenda similique quas debitis atque. Molestiae, consequuntur accusamus.
            Accusamus aliquid facere tempora! Sequi quasi cumque officia aliquam earum autem illo consequuntur repudiandae eligendi quam voluptatibus praesentium, atque inventore amet alias nemo minus facere nostrum adipisci, distinctio ad esse?
            Consequatur tempore ea totam sapiente adipisci qui, deleniti vero explicabo dolore numquam fuga culpa aliquid nulla nesciunt ipsa mollitia aspernatur error vel reprehenderit animi earum fugiat voluptatum quis? Itaque, natus.
            A mollitia, aliquam dolor expedita, officiis corrupti accusantium dolores, quod quis consequatur libero voluptatum repellat iure dolorum distinctio! Id, illo fugit minima voluptate asperiores accusamus quaerat ad vitae laudantium non.
            Minima soluta quae praesentium id officiis deserunt dolore, saepe quia cumque eum recusandae unde, dolorem delectus fugiat nemo, eius ad accusantium aliquam officia! Repellendus ad, illo aliquam quam nemo at.
            Consectetur, odit laborum! Sunt, dolorem quas numquam dolore dicta nam unde nulla, cupiditate temporibus eos ullam minus rerum architecto porro id at ratione dolor, ex illum quisquam aut esse et!
            Quo maiores consequatur, vero provident similique pariatur exercitationem suscipit ducimus placeat, et perspiciatis qui ratione hic distinctio animi dolorem vitae earum libero veritatis nemo! Assumenda, voluptas. Ab eaque voluptatibus soluta?
            Blanditiis, inventore? Neque est autem ut distinctio voluptatem voluptate asperiores inventore minus sunt voluptas ducimus nisi corporis quis, earum doloribus eveniet rerum odio architecto eos, odit eligendi eius corrupti quasi.
            Quam ratione repellat ipsum, quisquam, numquam nesciunt explicabo quas animi inventore, deleniti culpa asperiores modi doloribus suscipit! Quae, sed. Nisi aut velit odit aspernatur culpa quibusdam est maxime deleniti nihil.
            Ipsum enim architecto libero odit? Error, iure pariatur quod recusandae accusantium illum perferendis. Dolor sapiente adipisci eveniet cumque quisquam voluptatibus non obcaecati quo laboriosam itaque. Inventore quaerat cum repudiandae ipsam!
            Soluta nihil iste non quidem repellendus quaerat rem, placeat, tempora officia, eaque fugiat? Ipsa quo aliquid reprehenderit ullam voluptatem labore velit nulla ex sed beatae, culpa unde facilis natus dicta?
            Suscipit fuga sit, doloribus, illo qui maxime non hic magnam soluta voluptatum eum laudantium deleniti. Adipisci fugiat voluptate explicabo natus earum eius hic, sequi aperiam ducimus soluta tempore quis. Obcaecati!
            Ad nulla nam earum tempora repellendus doloribus quasi nobis soluta accusantium aliquid corrupti alias voluptatum, distinctio, animi dicta temporibus in nesciunt? Cumque perferendis laboriosam dolorum animi ducimus assumenda soluta earum.
            Nostrum ipsam quam in ullam tempora nihil officiis ratione aspernatur quos soluta. Impedit voluptate praesentium dolorem odit! Dolorum dignissimos reprehenderit dolor hic minima. Assumenda unde voluptatum, molestias amet asperiores expedita?
            Amet commodi accusantium reiciendis labore totam, ea quia officia aliquam! Quis illum laboriosam repudiandae quae iusto inventore eius esse id rem non, laborum hic quaerat eos accusantium amet dolorum laudantium!
            Dolorem harum eveniet accusamus rerum voluptatem perspiciatis sed delectus magnam doloribus aspernatur ut accusantium officia facere necessitatibus, dolorum, quos aut recusandae. Autem aliquam tempore possimus, vero laboriosam consequuntur quia iste?
            Nobis sed, minima ratione pariatur id dicta neque atque obcaecati odit porro similique tempore quisquam corrupti natus hic itaque deserunt alias. Officia error aspernatur quidem obcaecati, itaque a enim. Obcaecati!</p>
        </div>
    </div>
  )
}
